# -*- coding: utf-8 -*-
"""example_st.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_SI7x7T7fjGVzr-iscEs0SarRG1RWbeI
"""

import streamlit as st
st.write('Hello, *World!* :sunglasses:')